apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: built-demo
data:
  nginx.conf: |
    server {
      listen 3087;
      server_name localhost;

      location / {
        root /usr/share/nginx/html/;
        index index.html;
        autoindex on;
      }

      location /api/v1/ {
        proxy_pass http://article-backend:8080/api/v1/;
      }
    }
